In [1]:
5/2

2.5

In [2]:
5//2

2

In [3]:
5**2

25

In [4]:
a="jyothi"

In [5]:
b="rmayi"

In [6]:
print(a+b)

jyothirmayi


In [8]:
10*" jyothi"

' jyothi jyothi jyothi jyothi jyothi jyothi jyothi jyothi jyothi jyothi'

In [15]:
nums=[1,2,3,4,5]
names=["jyo","priya","shiv"]
print(nums)
print(names)

[1, 2, 3, 4, 5]
['jyo', 'priya', 'shiv']


In [21]:
mil=[nums,names]

In [17]:
nums.append(6)

In [18]:
nums

[1, 2, 3, 4, 5, 6]

In [19]:
nums.insert(2,2.5)

In [20]:
nums

[1, 2, 2.5, 3, 4, 5, 6]

In [22]:
nums.remove(2.5)

In [23]:
nums

[1, 2, 3, 4, 5, 6]

In [24]:
nums.pop(3)

4

In [25]:
nums

[1, 2, 3, 5, 6]

In [31]:
nums.extend([7,8,9,10])

In [32]:
nums

[1, 2, 3, 5, 6, 7, 8, 9, 10]

In [33]:
nums.insert(3,4)

In [34]:
nums

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
min(nums)

1

In [36]:
max(nums)

10

In [37]:
sum(nums)

55

In [38]:
tup=(5,6,7)

In [39]:
tup

(5, 6, 7)

In [45]:
min(tup)

5

In [46]:
max(tup)

7

In [47]:
sum(tup)

18

In [48]:
s={11,12,13,14,15}

In [49]:
s

{11, 12, 13, 14, 15}

In [50]:
id(s)

1432539274824

In [51]:
id(nums)

1432540033224

In [52]:
id(tup)

1432538624720

In [53]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [55]:
d={"jyo":"samsung","priya":"mi","shiv":"redmi"}

In [58]:
bin(10)

'0b1010'

In [59]:
0b1010

10

In [60]:
oct(25)

'0o31'

In [61]:
0o31

25

In [62]:
hex(30)

'0x1e'

In [64]:
0x1e

30

In [65]:
a=6

In [66]:
b=8

In [67]:
a,b=b,a

In [68]:
a

8

In [69]:
b

6

In [70]:
~1

-2

In [71]:
~0

-1

In [72]:
~12

-13

In [73]:
import math

In [74]:
print(math.sqrt(25))

5.0


In [75]:
print(math.floor(2.5))

2


In [76]:
print(math.ceil(2.5))

3


In [77]:
print(math.pow(3,2))

9.0


In [78]:
help("math")

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of

In [96]:
for i in range(5):
    for j in range(5):
        print("$",end=" ")
    print()

$ $ $ $ $ 
$ $ $ $ $ 
$ $ $ $ $ 
$ $ $ $ $ 
$ $ $ $ $ 


In [97]:
from numpy import *

In [99]:
arr=array([1,2,3,4,5])
print(arr.dtype)

int32


In [100]:
arr=linspace(0,5)

In [101]:
arr

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [102]:
arr=linspace(0,5,3)
print(arr)

[0.  2.5 5. ]


In [103]:
arr=arange(1,5,2)
print(arr)

[1 3]


In [104]:
arr=logspace(0,5,2)
print(arr)

[1.e+00 1.e+05]


In [106]:
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [107]:
arr=ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [108]:
arr=array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [112]:
arr=array([1,2,3,4,5])
arr+=5
print(arr)

[ 6  7  8  9 10]


In [113]:
arr

array([ 6,  7,  8,  9, 10])

In [129]:
arr1=[11,12,13,14,15]

In [124]:
arr1

[11, 12, 13, 14, 15]

In [125]:
arr=arr1

In [126]:
print(arr)
print(arr1)

[11, 12, 13, 14, 15]
[11, 12, 13, 14, 15]


In [4]:
0b1001001

73