In [42]:
import pandas as pd

In [43]:
df=[2,4,6,8,10]
df1=[1,3,5,7,9]

In [44]:
a=pd.Series(df)
b=pd.Series(df1)
print(a)
print(b)
print("sum",a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0    1
1    3
2    5
3    7
4    9
dtype: int64
sum 0     3
1     7
2    11
3    15
4    19
dtype: int64
sub 0    1
1    1
2    1
3    1
4    1
dtype: int64
mul 0     2
1    12
2    30
3    56
4    90
dtype: int64
div 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [51]:
df=pd.DataFrame({"a":[2,4,6,8,10],"b":[1,3,5,7,9,]})
df["sum"]=df["a"]+df["b"]
df["sub"]=df["a"]-df["b"]
df["mul"]=df["a"]*df["b"]
df["div"]=df["a"]/df["b"]
df

a  b  sum  sub  mul       div
0   2  1    3    1    2  2.000000
1   4  3    7    1   12  1.333333
2   6  5   11    1   30  1.200000
3   8  7   15    1   56  1.142857
4  10  9   19    1   90  1.111111

## write a numpy program to create a 3X3 matrix with values ranging from 2 to 10

In [2]:
import numpy as np

In [3]:
x=np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
for row in range(5):
    for col in range(5):
        if row==0 or col==1 or row==4 or col==4:
            print('1',end=" ")
        else:
            print("0",end=" ")
    print()

1 1 1 1 1 
0 1 0 0 1 
0 1 0 0 1 
0 1 0 0 1 
1 1 1 1 1 


In [5]:
n=int(input())
for row in range(n):
    for col in range(n):
        if row==0 or col==0 or row==n-1 or col==n-1:
            print('1',end=" ")
        else:
            print("0",end=" ")
    print()

7
1 1 1 1 1 1 1 
1 0 0 0 0 0 1 
1 0 0 0 0 0 1 
1 0 0 0 0 0 1 
1 0 0 0 0 0 1 
1 0 0 0 0 0 1 
1 1 1 1 1 1 1 


In [80]:
import numpy as np

In [82]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
n=int(input())
b=np.zeros((n,n))
b[1:-1,1:-1]=1
b

4


array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [95]:
n=int(input())
b=np.ones((n,n))
a=n//2
b[a:-a,a:-a]=0
b

7


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [133]:
l=[2,3,1,4,8,2,4,3]
sorted(l[:4])+sorted(l[4:],reverse=True)

[1, 2, 3, 4, 8, 4, 3, 2]

In [126]:
sorted(l[::-1])